### PR TITLE
able to use with angular 6

### PR DESCRIPTION
**Pull request by lordoliver**
update to angular 6
fix rxjs usage
fix http-import
upgrade typscript
increase major version (has to be major, as anguar also upgrade major version)

### CODE REVIEW

**Comment by SamirHodzic** [comment]
Hey @lordoliver, thanks for your PR. This seems promising, but not able atm to test it with this angular version. I'll reopen PR to try to trigger travis (seems bugged).

**Comment by lordoliver** [comment]
hm, have to use 0.0 version for dev dependencies?

**Comment by SamirHodzic** [comment]
Looks more like forced node version for travis. Let me check it out quickly.

**Comment by lordoliver** [comment]
seems like we have to upgrade codalizer. I will look tomorrow

**Comment by SamirHodzic** [comment]
in `.travis.yml` node version should be changed to:
```yaml
node_js:
  - '7'
```

**Comment by lordoliver** [comment]
I don't know, why 7, but here you are ;-)

**Comment by lordoliver** [comment]
I think your build failed because of network errors.

**Comment by lordoliver** [comment]
anything else now? the build is fine?

**Comment by diegomtzb** [comment]
Hello. I am trying to deploy to production with angular 6 and still gettting this error. What could I do to check? 
Thank you very much.

**Pull request merged**
